### ISSUE TITLE
Overriding `publicPath` breaks

### ISSUE THREAD

**Issue by SimenB** [webpack/extract-text-webpack-plugin#65]
The following config
```js
{
    test: /\.css$/,
    loader: ExtractTextPlugin.extract('style', 'css', { publicPath: '../' })
}
```
results in this css
```css
table.dataTable thead .sorting_desc_disabled {
  background: url([object Object]) no-repeat center right;
}
```
